---
title: "Gene expression exploration"
author: "Urwah Nawaz"
date: "2023-08-31"
output: 
  html_document:
    code_folding: hide
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
    autodep = TRUE,
    eval = TRUE,
	echo = FALSE,
	warning = FALSE,
	message = FALSE
)
```

# Set-up 

```{r libraries include=FALSE}
libs = c("dplyr", "ggplot2", "reshape2", "tools", "magrittr", "tibble", "readxl", 
         "data.table", "scales", "tidyr", "reshape2", "stringr", "tidyverse", "readxl", "corrplot", "viridis", 
         "sunburstR", "pheatmap")
libsLoaded <- lapply(libs,function(l){suppressWarnings(suppressMessages(library(l, character.only = TRUE)))})
library(EnsDb.Hsapiens.v86)
```

```{r annotations}
gene2symbol = genes(EnsDb.Hsapiens.v86, return.type="DataFrame") %>%
    as.data.frame()
gene2symbol %<>% 
    dplyr::select("EnsemblID" = "gene_id", gene_name)

```

```{r load-exp}
brain.dir =file.path("/home/neuro/Documents/BrainData/Bulk")
e <- list()
  
e$GTEx <- read.csv(file.path(brain.dir, "/GTEx/Formatted/GTEx-exp.csv"), 
                       check.names = FALSE, row.names = 1)
e$PE <- read.csv(file.path(brain.dir, "/PsychEncode/Formatted/PsychEncode-exp.csv"), 
                     row.names =1, check.names = FALSE) %>% 
  column_to_rownames("EnsemblID")
e$BSpan <- read.csv(file.path(brain.dir, "/BrainSpan/Formatted/BrainSpan-exp.csv"),
                        check.names = FALSE, row.names=1)
e$BSeq <- read.csv(file.path(brain.dir,"/Brainseq/Formatted/BrainSeq-exp.csv"), 
                       check.names = FALSE, row.names = 1)

e$HDBR <- read.csv(file.path(brain.dir, "/HDBR/Formatted/HDBR-exp.csv"), 
                       check.names = FALSE, row.names = 1) %>% 
  column_to_rownames("EnsemblID")

e$Ram <- read.csv(file.path(brain.dir, "/Ramakar/Formatted/Ramaker-exp.csv"), 
                       check.names = FALSE, row.names = 1) %>% 
  column_to_rownames("EnsemblID")
```

```{r load-md}
md = list()
md$GTEx <- read.csv(file.path(brain.dir, "/GTEx/Formatted/GTEx-metadata.csv"), 
                       check.names = FALSE, row.names = 1)
md$PE <- read.csv(file.path(brain.dir,"/PsychEncode/Formatted/PsychEncode-metadata.csv"),
                  check.names = FALSE)
md$BSeq <- read.csv(file.path(brain.dir,"/Brainseq/Formatted/BrainSeq-metadata.csv"), 
                       check.names = FALSE)
md$HDBR <- read.csv(file.path(brain.dir, "/HDBR/Formatted/HDBR-metadata.csv"), 
                       check.names = FALSE, row.names = 1) 
md$Ram <- read.csv(file.path(brain.dir, "/Ramakar/Formatted/Ramaker-metadata.csv"),
                       check.names = FALSE, row.names = 1)

md$BSpan <- read.csv(file.path(brain.dir,
                               "/BrainSpan/Formatted/BrainSpan-metadata.csv"),
                     check.names = FALSE)
  


```

# Exploration of genes for BITHub 

```{r}
genes_of_interest = c("FOXG1", "ZIC2")
exp_data = list()
datasets = c("BSpan", "GTEx", "BSeq", "PE", "Ram", "HDBR")
for (x in datasets) {
  message(paste("Subsetting samples for", x))
  dataset = e[[x]]
  md_sub = md[[x]]
  name = x
  sub = dataset %>% 
    as.data.frame() %>%
    rownames_to_column("EnsemblID") %>%
    left_join(gene2symbol, by = "EnsemblID") %>% 
    dplyr::filter(gene_name %in% genes_of_interest) %>% 
    melt() %>%
    dplyr::rename("SampleID" = "variable", "Exp" = "value") %>% 
    mutate(Dataset = x) %>% 
    left_join(md_sub %>% 
                dplyr::select(SampleID, Regions,
                              StructureAcronym, Period, 
                              AgeInterval), by = "SampleID")
  exp_data[[paste0(name)]] = sub 
  
}

```

```{r}
rm(e)
```

- FOXG1, ZIC2 and 


```{r}
exp_data %>% 
  do.call(rbind, .) %>% 
    mutate(AgeInterval = factor(AgeInterval, 
                              levels = c("4-7pcw", "8-9pcw",
                                         "10-12pcw", "13-15pcw", "16-18pcw",
                                         "19-24pcw", "25-38pcw", "0-5mos",
                                         "6-18mos", "19mos-5yrs", "6-11yrs",
                                         "12-19yrs", "20-29yrs", "30-39yrs",
                                         "40-49yrs", "50-59yrs", "60-69yrs",
                                         "70-79yrs", "80-89yrs", "90-99yrs"))) %>% 
  ggplot(aes(x = AgeInterval, y =log(Exp), fill = Regions)) + geom_boxplot() +  
  theme_bw() +
  
  #scale_fill_manual(values= c("Cerebellum" = "#FFD256",
   #                                        "Subcortex" = "#838DE0",
    #                                       "Cortex" = "#E85571", 
     #                                      "Spinal cord" = "#C6D14A", 
      #                                     "Forebrain", 
       #                                    "Midbrain", 
        #                                   "Hindbrain")) +
  facet_wrap(gene_name~Dataset, scales = "free", nrow = 2) + ylim(-6,6)
  theme(legend.position = "none")
  
  
```


<!-- # ```{r fig.width = 10} -->
<!-- # e$Raw$BSpan %>% -->
<!-- #   as.data.frame() %>% -->
<!-- #   rownames_to_column("EnsemblID") %>% -->
<!-- #     left_join(gene2symbol, by = "EnsemblID") %>%  -->
<!-- #     dplyr::filter(gene_name == "FOXG1") %>%  -->
<!-- #     dplyr::select(-gene_name) %>%  -->
<!-- #     column_to_rownames("EnsemblID") %>%  -->
<!-- #     melt() %>%  -->
<!-- #     dplyr::rename("SampleID" = "variable", "Exp" = "value") %>% -->
<!-- #   mutate(Dataset = "BrainSpan") %>%  -->
<!-- #   left_join(md$BSpan %>%  -->
<!-- #               dplyr::select(SampleID, Regions, -->
<!-- #                             StructureAcronym, Period,  -->
<!-- #                             AgeInterval), by = "SampleID") %>% -->
<!-- #   rbind(e$Raw$GTEx %>%  -->
<!-- #           rownames_to_column("EnsemblID") %>% -->
<!-- #       left_join(gene2symbol, by = "EnsemblID") %>%  -->
<!-- #       dplyr::filter(gene_name == "FOXG1") %>%  -->
<!-- #       dplyr::select(-gene_name) %>%  -->
<!-- #       column_to_rownames("EnsemblID") %>%  -->
<!-- #       melt() %>%  -->
<!-- #       dplyr::rename("SampleID" = "variable", "Exp" = "value") %>% -->
<!-- #       mutate(Dataset = "GTEx") %>% -->
<!-- #       left_join(md$GTEx %>%  -->
<!-- #               dplyr::select(SampleID, Regions, -->
<!-- #                             StructureAcronym, Period,  -->
<!-- #                             AgeInterval), by = "SampleID")) %>% -->
<!-- #   mutate(AgeInterval = factor(AgeInterval,  -->
<!-- #                               levels = c("4-7pcw", "8-9pcw", -->
<!-- #                                          "10-12pcw", "13-15pcw", "16-18pcw", -->
<!-- #                                          "19-24pcw", "25-38pcw", "0-5mos", -->
<!-- #                                          "6-18mos", "19mos-5yrs", "6-11yrs", -->
<!-- #                                          "12-19yrs", "20-29yrs", "30-39yrs", -->
<!-- #                                          "40-49yrs", "50-59yrs", "60-69yrs", -->
<!-- #                                          "70-79yrs", "80-89yrs", "90-99yrs"))) %>% -->
<!-- #     ggplot(aes(x = AgeInterval, y =log(Exp), fill = Regions)) + geom_boxplot() +   -->
<!-- #   theme_bw() + scale_fill_manual(values= c("Cerebellum" = "#FFD256", -->
<!-- #                                            "Subcortex" = "#838DE0", -->
<!-- #                                            "Cortex" = "#E85571")) + -->
<!-- #   facet_wrap(~Dataset, scales = "free", nrow = 2) + ylim(-6,6) -->
<!-- #   theme(legend.position = "none") -->
<!-- #      -->
<!-- #  -->
<!-- # ``` -->

<!-- # ```{r} -->
<!-- # e$Raw$BSpan %>% -->
<!-- #   as.data.frame() %>% -->
<!-- #   rownames_to_column("EnsemblID") %>% -->
<!-- #     left_join(gene2symbol, by = "EnsemblID") %>%  -->
<!-- #     dplyr::filter(gene_name == "ZIC2") %>%  -->
<!-- #     dplyr::select(-gene_name) %>%  -->
<!-- #     column_to_rownames("EnsemblID") %>%  -->
<!-- #     melt() %>%  -->
<!-- #     dplyr::rename("SampleID" = "variable", "Exp" = "value") %>% -->
<!-- #   mutate(Dataset = "BrainSpan") %>%  -->
<!-- #   left_join(md$BSpan %>%  -->
<!-- #               dplyr::select(SampleID, Regions, -->
<!-- #                             StructureAcronym, Period,  -->
<!-- #                             AgeInterval), by = "SampleID") %>% -->
<!-- #   rbind(e$Raw$GTEx %>%  -->
<!-- #           rownames_to_column("EnsemblID") %>% -->
<!-- #       left_join(gene2symbol, by = "EnsemblID") %>%  -->
<!-- #       dplyr::filter(gene_name == "ZIC2") %>%  -->
<!-- #       dplyr::select(-gene_name) %>%  -->
<!-- #       column_to_rownames("EnsemblID") %>%  -->
<!-- #       melt() %>%  -->
<!-- #       dplyr::rename("SampleID" = "variable", "Exp" = "value") %>% -->
<!-- #       mutate(Dataset = "GTEx") %>% -->
<!-- #       left_join(md$GTEx %>%  -->
<!-- #               dplyr::select(SampleID, Regions, -->
<!-- #                             StructureAcronym, Period,  -->
<!-- #                             AgeInterval), by = "SampleID")) %>% -->
<!-- #   mutate(AgeInterval = factor(AgeInterval,  -->
<!-- #                               levels = c("4-7pcw", "8-9pcw", -->
<!-- #                                          "10-12pcw", "13-15pcw", "16-18pcw", -->
<!-- #                                          "19-24pcw", "25-38pcw", "0-5mos", -->
<!-- #                                          "6-18mos", "19mos-5yrs", "6-11yrs", -->
<!-- #                                          "12-19yrs", "20-29yrs", "30-39yrs", -->
<!-- #                                          "40-49yrs", "50-59yrs", "60-69yrs", -->
<!-- #                                          "70-79yrs", "80-89yrs", "90-99yrs"))) %>% -->
<!-- #     ggplot(aes(x = AgeInterval, y =log(Exp), fill = Regions)) + geom_boxplot() +   -->
<!-- #   theme_bw() + scale_fill_manual(values= c("Cerebellum" = "#FFD256", -->
<!-- #                                            "Subcortex" = "#838DE0", -->
<!-- #                                            "Cortex" = "#E85571")) + -->
<!-- #   facet_wrap(~Dataset, scales = "free", nrow = 2) + ylim(-6,6) -->
<!-- #   theme(legend.position = "none") -->
<!-- #      -->
<!-- # ``` -->
<!-- #  -->
<!-- # ```{r} -->
<!-- #  -->
<!-- #  -->
<!-- # exp_data = list() -->
<!-- # dataset = c("BSpan", "GTEx", "BSeq", "PE", "Ram", "HDBR") -->
<!-- # for (x in dataset) { -->
<!-- #   message(paste("Subsetting samples for", x)) -->
<!-- #   dataset = e[[x]] -->
<!-- #   dataset %<>%  -->
<!-- #     as.data.frame() %>% -->
<!-- #   rownames_to_column("EnsemblID") %>% -->
<!-- #     left_join(gene2symbol, by = "EnsemblID") %>%  -->
<!-- #     dplyr::rename("SampleID" = "variable", "Exp" = "value") %>%  -->
<!-- #     mutate(Dataset = x) %>%  -->
<!-- #     left_join(md[[x]] %>%  -->
<!-- #                    dplyr::select(SampleID, Regions, -->
<!-- #                             StructureAcronym, Period,  -->
<!-- #                             AgeInterval), by = "SampleID") -->
<!-- #   exp_data[paste(x)] = dataset -->
<!-- #    -->
<!-- # } -->
<!-- # ``` -->
<!-- #  -->
<!-- # ```{r} -->
<!-- #  -->
<!-- # e$Raw$BSpan %>% -->
<!-- #   as.data.frame() %>% -->
<!-- #   rownames_to_column("EnsemblID") %>% -->
<!-- #     left_join(gene2symbol, by = "EnsemblID") %>%  -->
<!-- #     dplyr::filter(gene_name == "DLX1") %>%  -->
<!-- #     dplyr::select(-gene_name) %>%  -->
<!-- #     column_to_rownames("EnsemblID") %>%  -->
<!-- #     melt() %>%  -->
<!-- #     dplyr::rename("SampleID" = "variable", "Exp" = "value") %>% -->
<!-- #   mutate(Dataset = "BrainSpan") %>%  -->
<!-- #   left_join(md$BSpan %>%  -->
<!-- #               dplyr::select(SampleID, Regions, -->
<!-- #                             StructureAcronym, Period,  -->
<!-- #                             AgeInterval), by = "SampleID") %>% -->
<!-- #   rbind(e$Raw$GTEx %>%  -->
<!-- #           rownames_to_column("EnsemblID") %>% -->
<!-- #       left_join(gene2symbol, by = "EnsemblID") %>%  -->
<!-- #       dplyr::filter(gene_name == "DLX1") %>%  -->
<!-- #       dplyr::select(-gene_name) %>%  -->
<!-- #       column_to_rownames("EnsemblID") %>%  -->
<!-- #       melt() %>%  -->
<!-- #       dplyr::rename("SampleID" = "variable", "Exp" = "value") %>% -->
<!-- #       mutate(Dataset = "GTEx") %>% -->
<!-- #       left_join(md$GTEx %>%  -->
<!-- #               dplyr::select(SampleID, Regions, -->
<!-- #                             StructureAcronym, Period,  -->
<!-- #                             AgeInterval), by = "SampleID")) %>% -->
<!-- #   mutate(AgeInterval = factor(AgeInterval,  -->
<!-- #                               levels = c("4-7pcw", "8-9pcw", -->
<!-- #                                          "10-12pcw", "13-15pcw", "16-18pcw", -->
<!-- #                                          "19-24pcw", "25-38pcw", "0-5mos", -->
<!-- #                                          "6-18mos", "19mos-5yrs", "6-11yrs", -->
<!-- #                                          "12-19yrs", "20-29yrs", "30-39yrs", -->
<!-- #                                          "40-49yrs", "50-59yrs", "60-69yrs", -->
<!-- #                                          "70-79yrs", "80-89yrs", "90-99yrs"))) %>% -->
<!-- #     ggplot(aes(x = AgeInterval, y = Exp, fill = Regions)) + geom_boxplot() +   -->
<!-- #   theme_bw() + scale_fill_manual(values= c("Cerebellum" = "#FFD256", -->
<!-- #                                            "Subcortex" = "#838DE0", -->
<!-- #                                            "Cortex" = "#E85571")) + -->
<!-- #   facet_wrap(~Dataset, scales = "free", nrow = 2) + ylim(-6,6) -->
<!-- #   theme(legend.position = "none") -->
<!-- #  -->
<!-- #    -->
<!-- #   md$BSpan[256,] -->
<!-- # ``` -->

