---
title: "Recount Metadata pre-processing and correlations"
author: "Urwah Nawaz"
date: "2023-07-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
    autodep = TRUE,
    eval = TRUE,
	echo = FALSE,
	warning = FALSE,
	message = FALSE
)
```

# Setup 

```{r libraries}
library(recount3)
library(DT)
library(dplyr)
library(tidyr)
source("functions.R")
library(pander)
library(gridExtra)
library(variancePartition)
library(corrplot)
library(edgeR)
```

```{r}
annot =  read.csv("../annotations/Recount-annotations.csv", header=TRUE, check.names = FALSE, sep = ",")
```

# Background 


# Datasets 


## Ramakar et al (2017)

```{r}
ramakar = recount3::create_rse_manual(
  project = "SRP073813",
  project_home = "data_sources/sra",
  organism = "human",
  annotation = "gencode_v29",
  type = "gene"
)


ramakar.manual = read.table("/home/neuro/Documents/BrainData/Bulk/Ramakar/sra.gene_sums.SRP073813.G026", header=TRUE)

ramakar.refine = read.table("/home/neuro/Documents/BrainData/Bulk/Ramakar/SRP073813/SRP073813.tsv", sep = "\t", header=TRUE)
```

```{r sra-dataset}
sra_data = colData(ramakar) %>% 
  as.data.frame() %>% 
  dplyr::select(contains("sra")) 


md.sra = sra_data %>%
  dplyr::select("sra.sample_attributes") %>%
  separate(sra.sample_attributes, c("Age", "pH", "StructureAcronym", "Diagnosis", "Ethnicity", "Sex",
                                    "PMI", "SourceName", "Tissue"), sep="\\|") %>% 
  mutate(Age = gsub(".*;;","", Age), 
         pH = gsub(".*;;","", pH), 
         StructureAcronym = gsub(".*;;","", StructureAcronym),
         Diagnosis = gsub(".*;;","", Diagnosis), 
         Ethnicity = gsub(".*;;","", Ethnicity), 
         Sex = gsub(".*;;","", Sex), 
         PMI = gsub(".*;;","", PMI)) %>% 
  dplyr::select(-c("SourceName", "Tissue")) %>% 
  mutate(Sex = ifelse(Sex == "male", "M", "F"), 
         StructureAcronym = gsub("nAcc","NAC", StructureAcronym), 
         StructureAcronym = gsub("AnCg", "ACC", StructureAcronym)) %>%
  mutate(Regions =  add_feature(.$StructureAcronym, regions),
        Age_rounded = as.character(sapply(na.omit(as.numeric(.$Age)), num_to_round)), 
        Period = c("Postnatal"), 
        Age = as.numeric(Age), 
        pH = as.numeric(pH), 
        PMI = as.numeric(PMI)) %>%
  mutate(AgeInterval = add_feature(.$Age_rounded , age_intervals)) %>%
  rownames_to_column("SampleID")
```


```{r}
md.refine.bio = read.table("/home/neuro/Documents/BrainData/Bulk/Ramakar/SRP073813/metadata_SRP073813.tsv", header=TRUE,
                           sep = "\t")

md.refine.bio %<>% 
  as.data.frame() %>%
  mutate(DonorID = gsub("_.*","", refinebio_title))  %>% 
  dplyr::rename("SampleID" = "refinebio_accession_code")




```

```{r recount}
md = colData(ramakar) %>% 
  as.data.frame() %>%
  dplyr::select(-contains("2"))
colnames(md) = annot$BITColumnName[match(colnames(md), annot$RecountName)]
md = full_join(md, md.sra)

md = full_join(md, md.refine.bio)
#md_names = colnames(md) %>% as.data.frame()
#write.csv(md_names, file = "../annotations/Ramaker-2017-metadata-annot.csv")
```


```{r}
md.clean = md %>% select_if(~ !any(is.na(.)))
md.clean = md.clean[vapply(md.clean, function(x) length(unique(x)) > 1, logical(1L))]
```

* Selection of metadata variables for subset 

```{r fig.height=30, fig.width=30}
M = cor(data.matrix(md.clean), use = "complete.obs")
corrplot(M, order='AOE')
```

```{r}
rowMeans(M, na.rm = TRUE) %>% scale() %>% as.data.frame() 
```

* Selection for variance Partition 

```{r}
ramakar_annot = read.csv("../annotations/Ramaker-2017-metadata-annot.csv", header=TRUE) %>% 
  dplyr::filter(Include..Yes.No....Interest == "Yes") %>% 
  dplyr::select(-c(Include..Yes.No....Interest))


knitr::kable(ramakar_annot)

md %<>% dplyr::select(contains(ramakar_annot$BITColumnName))
```

```{r fig.height=20, fig.width=20}
M = cor(data.matrix(md), use = "complete.obs")
corrplot(M)
```

* Preprocess counts from recount 

Best to use TPM 

```{r}
# #assay(ramakar, "counts") <- transform_counts(ramakar)
# #counts.ram = assay(ramakar,)
# assays(ramakar)$counts <- transform_counts(ramakar)
# 
# assays(ramakar)$tpm <- recount::getTPM(ramakar)
# 
# ram.tpm = assays(ramakar)$tpm %>% as.data.frame()
# 
# ram.tpm = assays(ramakar)$raw_counts


```

Filtering dataset 

```{r}
ramakar.cpm = ramakar.refine %>% 
  column_to_rownames("Gene") %>% 
  cpm()
```

```{r}
ram.before = log(ramakar.cpm + 0.01) %>%
    melt() %>%
    dplyr::filter(is.finite(value)) %>% 
    ggplot(aes(x=value, color = as.character( Var2))) +
    geom_density() +
    ggtitle("Before filtering") +
    labs(x = "logTPM", y = "Proportion of Genes") + 
    theme_bw() +
    theme(legend.position = "none")

ram.exp.filt <- thresh(ramakar.cpm)


ram.after =log(ram.exp.filt + 0.01) %>%
    melt() %>%
    dplyr::filter(is.finite(value)) %>% 
    ggplot(aes(x=value, color = as.character(Var2))) +
    geom_density() +
    ggtitle("After filtering") +
    labs(x = "logRPKM", y = "Proportion of Genes") + 
    theme_bw() +
    theme(legend.position = "none")

grid.arrange(ram.before, ram.after, ncol =2)
```

Variance partition 


```{r}
form.ram <- ~ Age + (1|StructureAcronym) + (1|Sex) + (1|Diagnosis) + PMI + pH
C.ram = canCorPairs(form.ram, md)
plotCorrMatrix(C.ram)
```

```{r}
md %<>% 
  dplyr::filter(SampleID %in% colnames(ram.exp.filt))
```

```{r}
varPar.ram <- fitExtractVarPartModel(ram.exp.filt, form.ram ,md )

```

```{r}
var.genes.ram = plotVarPart(varPar.ram)
var.total.ram =plotPercentBars(varPar.ram [1:10,] )
grid.arrange(var.genes.ram, var.total.ram , ncol = 2)
```


# Human developmental biology resource 

```{r}
hdbr = recount3::create_rse_manual(
  project = "ERP016243",
  type = "gene"
)
```


```{r}
assayNames(hdbr)
```