---
title: "Deconvolution"
author: "Urwah Nawaz"
date: "2023-01-03"
output:
  html_document:
    code_folding: hide
    toc: true
    toc_float: true
---

```{css toc-content, echo = FALSE}
#TOC {
  right: 270px;
  margin: 20px 0px 25px 0px;
}

.main-container {
    margin-left: 200px;
}
```

# Deconvolution with dtangle

```{r}
source("libraries.R")
source("functions.R")

load("../../Results/signatures/pfc_signatures.Rda")
load("../../DeconRNAShiny/sigsBrain.rda")
```

```{r}
bspan.exp = read.csv("/home/neuro/Documents/BrainData/Bulk/BrainSpan/Kang/genes_matrix_csv/Formatted/BrainSpan-exp.csv", row.names = 2, check.names = FALSE)[,-1]
bspan.md = read.csv("/home/neuro/Documents/BrainData/Bulk/BrainSpan/Kang/genes_matrix_csv/Formatted/BrainSpan-metadata.csv", row.names = 1, header= TRUE)
```


```{r}
stages.df = list()
stages.df[["Fetal"]] = c(paste(c(4:40), "pcw", sep = "_"))
stages.df[["Neonatal"]] =c(paste(c(0:10), "mos", sep = "_"))
#stages.df[["Infancy"]] =c(paste(c(0:10), "mos", sep = "_"))
stages.df[["Childhood"]] = paste(c(1:10), "yrs", sep = "_")
stages.df[["Adolescence"]] = paste(c(11:19), "yrs", sep = "_")
stages.df[["Adult"]] = paste(c(20:40), "yrs", sep = "_")


add_feature = function(feature_column, features){
    as.vector(sapply(feature_column, function(x){
        names(features)[sapply(features, function(f) x %in% f)]})) 
}

bspan.md = bspan.md %>% 
    mutate(Dev.stage = add_feature(.$Age, stages.df))

table(bspan.md$Dev.stage)
```




```{r}
stages = c("Fetal", "Neonatal","Infancy",  "Childhood","Adolescence", "Adult")

dtg_res = list()
for (stage in stages){
    sigs_dev = pfc_signatures$rpkm_all_neuro %>% 
        dplyr::select(contains(stage))
    
    dev_res = run_dtg(bspan.exp,sigs_dev) %>%
        as.data.frame() %>% 
        mutate(Sig = stage)
    
    dtg_res[[paste0(stage)]] = dev_res
}




## 2) run dtangle for MB

dtg_res$MB = run_dtg(bspan.exp,sigsBrain$MB) %>%
    as.data.frame() %>%
    mutate(Sig = "MB")
```



```{r}
stages = c("Fetal", "Neonatal", "Childhood","Adolescence", "Adult")
gof_res = list()

for (stage in stages){
    stage.md = bspan.md %>% dplyr::filter(Dev.stage == stage)
    stage.exp = bspan.exp %>% dplyr::select(stage.md$SampleID)
    dtg.stage =  dtg_res[[paste0(stage)]] %>% 
        as.data.frame() %>% 
        rownames_to_column("Sample") %>% 
        dplyr::filter(Sample %in% colnames(stage.exp)) %>% 
        column_to_rownames("Sample") %>% 
        dplyr::select(-contains(".Sig"))
    sigs_dev = pfc_signatures$rpkm_all_neuro %>% 
        dplyr::select(contains(stage))
    gof = write.gof(stage.exp, dtg.stage, sigs_dev) %>% 
        as.data.frame() %>% 
        mutate(sigs = paste0(stage, "_PFC_sig")) %>% 
        rownames_to_column("SampleID") %>%
        mutate_at(.vars = "SampleID", .funs = gsub, pattern = "\\X", replacement = "") %>% 
        mutate_at(.vars = "SampleID", .funs = gsub, pattern = "\\.", replacement = "-") %>%
        left_join(stage.md)
    gof_res[[paste0(stage, "_gof_res")]] = gof
    
    ## MultiBrain 
    
    dtg.MB = dtg_res$MB %>% 
        as.data.frame() %>% 
        rownames_to_column("Sample") %>% 
        dplyr::filter(Sample %in% colnames(stage.exp)) %>% 
        column_to_rownames("Sample") %>% 
        dplyr::select(-contains(".Sig"))
    
    gof.MB = write.gof(stage.exp, dtg.MB, sigsBrain$MB) %>% 
        as.data.frame() %>% 
        mutate(sigs = paste0(stage, "_MB_sig")) %>% 
        rownames_to_column("SampleID") %>%
        mutate_at(.vars = "SampleID", .funs = gsub, pattern = "\\X", replacement = "") %>% 
        mutate_at(.vars = "SampleID", .funs = gsub, pattern = "\\.", replacement = "-") %>%
        left_join(stage.md)
    
    gof_res[[paste0(stage, "_gof_MB")]] = gof.MB
    
}


```


```{r}
stages.df = list()
stages.df[["Fetal"]] = c(paste(c(4:40), "pcw", sep = "_"))
#stages.df[["Neonatal"]] =c(paste(c(0:10), "mos", sep = "_"))
stages.df[["Infancy"]] =c(paste(c(0:10), "mos", sep = "_"))
stages.df[["Childhood"]] = paste(c(1:10), "yrs", sep = "_")
stages.df[["Adolescence"]] = paste(c(11:19), "yrs", sep = "_")
stages.df[["Adult"]] = paste(c(20:40), "yrs", sep = "_")


add_feature = function(feature_column, features){
    as.vector(sapply(feature_column, function(x){
        names(features)[sapply(features, function(f) x %in% f)]})) 
}

bspan.md = bspan.md %>% 
    mutate(Dev.stage = add_feature(.$Age, stages.df))

table(bspan.md$Dev.stage)

```

```{r}
stages = c("Fetal", "Infancy", "Childhood","Adolescence", "Adult")
for (stage in stages){
    stage.md = bspan.md %>% dplyr::filter(Dev.stage == stage)
    stage.exp = bspan.exp %>% dplyr::select(stage.md$SampleID)
    dtg.stage =  dtg_res[[paste0(stage)]] %>% 
        as.data.frame() %>% 
        rownames_to_column("Sample") %>% 
        dplyr::filter(Sample %in% colnames(stage.exp)) %>% 
        column_to_rownames("Sample") %>% 
        dplyr::select(-contains(".Sig"))
    sigs_dev = pfc_signatures$rpkm_all_neuro %>% 
        dplyr::select(contains(stage))
    gof = write.gof(stage.exp, dtg.stage, sigs_dev) %>% 
        as.data.frame() %>% 
        mutate(sigs = paste0(stage, "_PFC_sig")) %>% 
        rownames_to_column("SampleID") %>%
        mutate_at(.vars = "SampleID", .funs = gsub, pattern = "\\X", replacement = "") %>% 
        mutate_at(.vars = "SampleID", .funs = gsub, pattern = "\\.", replacement = "-") %>%
        left_join(stage.md)
    gof_res[[paste0(stage, "_gof_res")]] = gof
    
    ## MultiBrain 
    
    dtg.MB = dtg_res$MB %>% 
        as.data.frame() %>% 
        rownames_to_column("Sample") %>% 
        dplyr::filter(Sample %in% colnames(stage.exp)) %>% 
        column_to_rownames("Sample") %>% 
        dplyr::select(-contains(".Sig"))
    
    gof.MB = write.gof(stage.exp, dtg.MB, sigsBrain$MB) %>% 
        as.data.frame() %>% 
        mutate(sigs = paste0(stage, "_MB_sig")) %>% 
        rownames_to_column("SampleID") %>%
        mutate_at(.vars = "SampleID", .funs = gsub, pattern = "\\X", replacement = "") %>% 
        mutate_at(.vars = "SampleID", .funs = gsub, pattern = "\\.", replacement = "-") %>%
        left_join(stage.md)
    
    gof_res[[paste0(stage, "_gof_MB")]] = gof.MB
    
}

```

```{r fig.height=10, fig.width=10}
gof_res %>% 
    do.call(rbind, .) %>% 
    ggplot(aes(sigs,r, fill = sigs)) + geom_violin() + facet_wrap(~Dev.stage, scales ="free_x") + geom_jitter() +
    theme(axis.text.x = element_blank(), 
          legend.position = "bottom") +  ylab("Goodness of fit (r)") + xlab("Signatures")


```
